# Generated by Django 6.0.7 on 2026-07-13 12:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=200, unique=True)),
                ('results_count', models.IntegerField(default=0)),
                ('last_searched_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date last searched')),
            ],
            options={
                'verbose_name_plural': 'search queries',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='query',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.searchquery'),
        ),
    ]
