# Generated by Django 6.0.7 on 2026-07-13 15:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


def clean_products(apps, schema_editor):
    """
    1) Zero out garbage prices that overflow DecimalField(12,2) — produced by
       an extract_numeric_price bug that concatenated original + discounted
       prices; the rows get correct prices on the next scrape.
    2) Keep the oldest product per (query, url) so the unique constraint
       can apply.
    """
    schema_editor.execute(
        "UPDATE products_product SET price = 0 WHERE price >= 10000000000"
    )
    Product = apps.get_model('products', 'Product')
    seen = set()
    # values_list avoids reading the price column while cleaning
    for pid, query_id, url in (
        Product.objects.exclude(url='').order_by('id')
        .values_list('id', 'query_id', 'url')
    ):
        key = (query_id, url)
        if key in seen:
            Product.objects.filter(pk=pid).delete()
        else:
            seen.add(key)


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_searchquery_product_query'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='HUF', max_length=8)),
                ('price_huf', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('recorded_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'price histories',
                'ordering': ['-recorded_date'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='first_seen',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='product',
            name='last_seen',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='product',
            name='price_huf',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='store',
            name='failure_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='store',
            name='last_success',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='currency',
            field=models.CharField(default='HUF', max_length=8),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='product',
            name='url',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='searchquery',
            name='last_searched_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date last searched'),
        ),
        migrations.AlterField(
            model_name='store',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='store',
            name='url',
            field=models.CharField(max_length=200),
        ),
        migrations.RunPython(clean_products, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(condition=models.Q(('url', ''), _negated=True), fields=('query', 'url'), name='unique_product_per_query_url'),
        ),
        migrations.AddField(
            model_name='pricehistory',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='products.product'),
        ),
    ]
